routes:
    home:       'Default:home'
    homeSync:       'Default:homeSync'
    khassida:     'Default:khassida'
    logout:     'Security:logout'
    register:     'Security:register'
    login:     'Security:login'
    profile:       'User:profile'
    contact:    'Default:contact'
    admin:       'Security:admin'



defaut_route: 'home'

db_config:
    name: 'sikar'
    host: 'localhost'
    user: 'root'
    pass: 'root'
